using System.Collections.Generic;

namespace Olden_Era___Template_Editor.Localization
{
    /// <summary>
    /// RU/EN UI string tables. Keys are stable ASCII identifiers referenced from XAML via
    /// <c>{DynamicResource S.X.Y}</c> and from code-behind via <c>L.Get("S.X.Y")</c>.
    /// Both tables MUST have identical key sets (enforced by a unit test).
    /// Only display text lives here — never logic tokens (SIDs, enum names, gameMode, Tag values).
    /// </summary>
    public static class Strings
    {
        public static readonly Dictionary<string, string> Ru = new()
        {
            // ── UI chrome (curated) ──
            ["S.Tab.Rules"]        = "Правила",
            ["S.Tab.MapZones"]     = "Карта и зоны",
            ["S.Tab.BonusesBans"]  = "Бонусы и баны",
            ["S.Tab.ExtraContent"] = "Доп. контент [ЭКСП.]",
            ["S.Hdr.Template"]     = "◆  ШАБЛОН",
            ["S.Hdr.Heroes"]       = "◆  ГЕРОИ",
            ["S.Hdr.GameRules"]    = "◆  ПРАВИЛА ИГРЫ",
            ["S.Hdr.Environment"]  = "◆  ОКРУЖЕНИЕ И ВСТРЕЧИ",
            ["S.Lbl.Preset"]       = "Пресет",
            ["S.Btn.PresetPick"]   = "— Выберите готовый шаблон —   ▾",
            ["S.Lbl.TemplateName"] = "Название шаблона",
            ["S.Lbl.MapSize"]      = "Размер карты",
            ["S.Chk.ExpMaps"]      = "Экспериментальные большие карты",
            ["S.Lbl.Players"]      = "Игроки",
            ["S.Lbl.HeroMin"]      = "Начальный лимит героев",
            ["S.Lbl.HeroMax"]      = "Макс. лимит героев",
            ["S.Lbl.HeroIncrement"]= "Прирост лимита за замок",
            ["S.Chk.SingleHero"]   = "Режим одного героя",
            ["S.Hint.Heroes"]      = "Ползунок, кнопки −/+ или ввод числа (Enter). Максимум — 12 (как в официальных шаблонах игры).",
            ["S.Btn.Generate"]     = "⚔  Создать шаблон",
            ["S.Btn.SaveTemplate"] = "💾  Сохранить шаблон",
            ["S.Btn.Editor"]       = "🗺 Редактор",
            ["S.Chk.ShowPreview"]  = "Показать превью",

            // ── MainWindow (extracted) ──
            ["S.M.001"] = "Сбросить настройки (Ctrl+N)",
            ["S.M.002"] = "Открыть настройки (Ctrl+O)",
            ["S.M.003"] = "Сохранить настройки (Ctrl+S)",
            ["S.M.004"] = "Сохранить настройки как… (Ctrl+Shift+S)",
            ["S.M.005"] = "Визуальный редактор зон (открыть текущий шаблон или загрузить .rmg.json)",
            ["S.M.006"] = "Русский язык",
            ["S.M.007"] = "Свернуть",
            ["S.M.008"] = "Развернуть",
            ["S.M.009"] = "Закрыть",
            ["S.M.010"] = "Обновить",
            ["S.M.011"] = "Что нового",
            ["S.M.012"] = "Позже",
            ["S.M.013"] = "Быстрый старт: готовые конфигурации, сгруппированные по типу режима",
            ["S.M.014"] = "Свой шаблон",
            ["S.M.015"] = "Добавляет размеры от 256x256 до 512x512. Официальные шаблоны заканчиваются на 240x240, поэтому большие карты могут не загрузиться, зависнуть или вести себя непредсказуемо.",
            ["S.M.016"] = "Меньше",
            ["S.M.017"] = "Можно ввести своё значение (Enter)",
            ["S.M.018"] = "Больше",
            ["S.M.019"] = "Основное условие победы",
            ["S.M.020"] = "Опыт законов фракций",
            ["S.M.021"] = "Опыт астрологии",
            ["S.M.022"] = "Поражение при потере стартового города",
            ["S.M.023"] = "День потери города",
            ["S.M.024"] = "Поражение при потере стартового героя",
            ["S.M.025"] = "Победа за удержание нейтр. города",
            ["S.M.026"] = "Дней удержания",
            ["S.M.027"] = "Правила гладиаторской арены",
            ["S.M.028"] = "Задержка арены",
            ["S.M.029"] = "День подсчёта арены",
            ["S.M.030"] = "Правила турнира",
            ["S.M.031"] = "Очков для победы",
            ["S.M.032"] = "Первый бой в день ",
            ["S.M.033"] = "Дней между боями",
            ["S.M.034"] = "Сохранять всю армию после боя",
            ["S.M.035"] = "Тип ландшафта",
            ["S.M.036"] = "Агрессия монстров",
            ["S.M.037"] = "Количество воды",
            ["S.M.038"] = "Шанс перехода нейтр.",
            ["S.M.039"] = "Неровность ландшафта",
            ["S.M.040"] = "Количество озёр",
            ["S.M.041"] = "Разрешить обход охраны (лазейки)",
            ["S.M.042"] = "◆  ТОПОЛОГИЯ",
            ["S.M.043"] = "Топология карты",
            ["S.M.044"] = "Размер зоны хаба",
            ["S.M.045"] = "Замки в хабе",
            ["S.M.046"] = "Соединять только через нейтр. зоны, если возможно",
            ["S.M.047"] = "Игра старается соединять зоны игроков только через нейтральные зоны. Если рядом нет нейтральной зоны, произойдёт прямое соединение с другим игроком.",
            ["S.M.048"] = "◆  НАСТРОЙКА ЗОН",
            ["S.M.049"] = "Расширенные настройки",
            ["S.M.050"] = "Доп. нейтральные зоны",
            ["S.M.051"] = "Замки в зонах игроков",
            ["S.M.052"] = "Одна фракция для всех замков в зоне игрока",
            ["S.M.053"] = "Игрок начинает со всеми замками в своей зоне",
            ["S.M.054"] = "Замки в нейтр. зонах",
            ["S.M.055"] = "Частота ресурсов",
            ["S.M.056"] = "Частота построек",
            ["S.M.057"] = "Сила нейтр. войск",
            ["S.M.058"] = "Сила границ/порталов",
            ["S.M.059"] = "Нейтральные зоны",
            ["S.M.060"] = "Нейтральные зоны с замком используют значение «Замки в нейтр. зонах».",
            ["S.M.061"] = "Слабая нейтр., без замка",
            ["S.M.062"] = "Слабая нейтр., с замком",
            ["S.M.063"] = "Средняя нейтр., без замка",
            ["S.M.064"] = "Средняя нейтр., с замком",
            ["S.M.065"] = "Сильная нейтр., без замка",
            ["S.M.066"] = "Сильная нейтр., с замком",
            ["S.M.067"] = "Мин. нейтралов между игроками",
            ["S.M.068"] = "Учитывается, только если выбранная топология, число нейтр. зон и настройки порталов это позволяют; иначе используется обычная раскладка связей.",
            ["S.M.069"] = "Генерировать дороги",
            ["S.M.070"] = "Создавать удалённые плацдармы",
            ["S.M.071"] = "Создавать доп. порталы",
            ["S.M.072"] = "Макс. число порталов",
            ["S.M.073"] = "Тонкая настройка зон [ЭКСПЕРИМЕНТ]",
            ["S.M.074"] = "Относительные веса регионов и разброс охраны для раскладки игры.",
            ["S.M.075"] = "Размер зоны игрока",
            ["S.M.076"] = "Размер нейтр. зоны",
            ["S.M.077"] = "Разброс силы охраны",
            ["S.M.078"] = "◆  СТАРТОВЫЕ БОНУСЫ",
            ["S.M.079"] = "Бонусы выдаются всем игрокам одинаково в начале игры.",
            ["S.M.080"] = "Удалить",
            ["S.M.081"] = "◆  БАНЫ",
            ["S.M.082"] = "Подключить ассеты установленной игры (полный список героев с именами)",
            ["S.M.083"] = "Без этой опции редактор работает полностью: встроенный проверенный список и цветные метки фракций. С опцией — из локальных файлов игры подгружается полный список героев с настоящими именами; ничего не загружается в сеть.",
            ["S.M.084"] = "Забаненные предметы",
            ["S.M.085"] = "Забаненные заклинания",
            ["S.M.086"] = "Забаненные герои",
            ["S.M.087"] = "◆  РАСШИРЕННОЕ",
            ["S.M.088"] = "Переопределение силы охраны (по строке: sid=значение)",
            ["S.M.089"] = "Экспериментальная функция. Генератор постарается дополнительно разместить всё по этим правилам, но ограничен доступным местом. Слишком много обязательного контента может привести к непредсказуемому поведению, особенно на малых картах и при малых зонах игроков.",
            ["S.M.090"] = "Зоны игроков",
            ["S.M.091"] = "◆  Шахты",
            ["S.M.092"] = "Добавить",
            ["S.M.093"] = "◆  Сокровища",
            ["S.M.094"] = "◆  Найм существ",
            ["S.M.095"] = "◆  Хранилища ресурсов",
            ["S.M.096"] = "◆  Полезные постройки",
            ["S.M.097"] = "◆  Постройки развития героя",
            ["S.M.098"] = "Удалить контент",
            ["S.M.099"] = "Под охраной",
            ["S.M.100"] = "У замка",
            ["S.M.101"] = "Дорога",
            ["S.M.102"] = "Любая",
            ["S.M.103"] = "Вплотную",
            ["S.M.104"] = "Близко",
            ["S.M.105"] = "Средне",
            ["S.M.106"] = "Далеко",
            ["S.M.107"] = "Очень далеко",
            ["S.M.108"] = "Сбросить по умолчанию",
            ["S.M.109"] = "Слабые нейтр. зоны",
            ["S.M.110"] = "Средние нейтр. зоны",
            ["S.M.111"] = "Сильные нейтр. зоны",
            ["S.M.112"] = "Зоны хаба",
            ["S.M.113"] = "⚠️ Настройки изменились — создайте новый шаблон перед сохранением, чтобы применить изменения.",

            // ── Zone editor (extracted) ──
            ["S.Ed.001"] = "🗺  Редактор зон",
            ["S.Ed.002"] = "📂 Загрузить .rmg.json",
            ["S.Ed.003"] = "➕ Зона",
            ["S.Ed.004"] = "🔗 Связать",
            ["S.Ed.005"] = "🗑 Удалить",
            ["S.Ed.006"] = "✓ Проверить",
            ["S.Ed.007"] = "💾 Сохранить .rmg.json",
            ["S.Ed.008"] = "⟲ Сброс вида",
            ["S.Ed.009"] = "↺ Авто-раскладка",
            ["S.Ed.010"] = "◆  ИНСПЕКТОР",
            ["S.Ed.011"] = "Выберите зону или связь на холсте.",
            ["S.Ed.012"] = "Готово.",
            ["S.Ed.ZoomIn"]  = "Приблизить",
            ["S.Ed.ZoomOut"] = "Отдалить",
            ["S.Ed.LegZones"]   = "Зоны:",
            ["S.Ed.LegPlayer"]  = "игрок",
            ["S.Ed.LegHub"]     = "хаб",
            ["S.Ed.LegNeutral"] = "нейтральная",
            ["S.Ed.LegConns"]   = "Связи:",
            ["S.Ed.LegDirect"]  = "прямая",
            ["S.Ed.LegPortal"]  = "портал",
            ["S.Ed.CanvasHint"] = "Колесо — зум · ЛКМ по фону — двигать холст · тяните зону · Del — удалить · Esc — отмена",
            ["S.Ed.ExportPng"]    = "🖼 PNG",
            ["S.EC.ExportTitle"]  = "Экспорт графа в PNG",
            ["S.EC.Exported"]     = "Изображение сохранено: {0}.",

            // ── Spell picker (extracted) ──
            ["S.Spell.001"] = "Выбор заклинания",
            ["S.Spell.002"] = "Бесплатно (0 маны)",
            ["S.Spell.003"] = "Добавить выбранное",
            ["S.Spell.004"] = "Отмена",

            // ── Item/ban picker (extracted) ──
            ["S.Item.001"] = "Выбор для бана",
            ["S.Item.002"] = "Свой ID:",
            ["S.Item.003"] = "Введите любой ID, которого нет в списке выше",
            ["S.Item.004"] = "Добавить свой",

            // ── Bonus picker (extracted) ──
            ["S.Bonus.001"] = "Добавить бонус",
            ["S.Bonus.002"] = "Тип бонуса",
            ["S.Bonus.003"] = "Заклинание",
            ["S.Bonus.004"] = "Множитель армии",
            ["S.Bonus.005"] = "Бонус к ходу",
            ["S.Bonus.006"] = "Стартовый предмет",
            ["S.Bonus.007"] = "Стартовое золото",
            ["S.Bonus.008"] = "Стартовые самоцветы",
            ["S.Bonus.009"] = "Стартовые кристаллы",
            ["S.Bonus.010"] = "Стартовая ртуть",
            ["S.Bonus.011"] = "Стартовая древесина",
            ["S.Bonus.012"] = "Стартовая руда",
            ["S.Bonus.013"] = "Применяется к",
            ["S.Bonus.014"] = "Стартовый герой",
            ["S.Bonus.015"] = "Все герои",
            ["S.Bonus.016"] = "Выбрать…",
            ["S.Bonus.017"] = "Сделать заклинание бесплатным (0 маны)",
            ["S.Bonus.018"] = "Множитель (напр. 2 = удвоенная стартовая армия)",
            ["S.Bonus.019"] = "Доп. клетки передвижения (0 = по умолчанию)",
            ["S.Bonus.020"] = "ID артефакта",
            ["S.Bonus.021"] = "Количество",

            // ── Update progress (extracted) ──
            ["S.Upd.001"] = "Обновление AuroraRMG",
            ["S.Upd.002"] = "Загрузка обновления…",
            ["S.Upd.003"] = "Подключение…",

            // ── Value-override picker (extracted) ──
            ["S.Vov.001"] = "Переопределение значений",
            ["S.Vov.002"] = "Сила охраны для выбранных:",
            ["S.Vov.003"] = "Сила охраны для всех отмеченных объектов",

            // ── Option combos (Rules / Map tabs) ──
            ["S.Topo.Balanced"] = "Сбалансированная",
            ["S.Topo.Random"]   = "Случайная",
            ["S.Topo.Ring"]     = "Кольцо",
            ["S.Topo.Hub"]      = "Хаб",
            ["S.Topo.Chain"]    = "Цепь",
            ["S.TopoDesc.Balanced"] = "Зоны размещаются концентрическими кольцами по уровню качества. Игроки на внешнем кольце, нейтральные зоны — на внутренних. Каждая зона соединяется с соседними на смежных кольцах.",
            ["S.TopoDesc.Random"]   = "Зоны размещаются в случайных позициях. Каждая зона соединяется со всеми граничащими — без фиксированной структуры.",
            ["S.TopoDesc.Ring"]     = "Все зоны расположены по кругу. Каждая зона соединяется с двумя соседними.",
            ["S.TopoDesc.Hub"]      = "Все зоны соединяются с общим центральным хабом. Игроки никогда не граничат напрямую.",
            ["S.TopoDesc.Chain"]    = "Зоны соединены прямой линией от одного конца к другому, без замыкания.",
            ["S.Terrain.FactionBased"] = "По фракции",
            ["S.Terrain.Random"]       = "Случайный микс",
            ["S.Terrain.Grass"]        = "Трава",
            ["S.Terrain.Snow"]         = "Снег",
            ["S.Terrain.Lava"]         = "Лава",
            ["S.Terrain.Sand"]         = "Песок",
            ["S.Terrain.Dirt"]         = "Грязь",
            ["S.Terrain.Deathland"]    = "Мёртвые земли",
            ["S.Terrain.Autumn"]       = "Осень",
            ["S.Aggr.Passive"]    = "Пассивная",
            ["S.Aggr.Normal"]     = "Обычная",
            ["S.Aggr.Aggressive"] = "Агрессивная",
            ["S.Water.None"]   = "Нет",
            ["S.Water.Small"]  = "Немного",
            ["S.Water.Medium"] = "Средне",
            ["S.Water.Large"]  = "Много",
            ["S.Victory.0"] = "Стандартная",
            ["S.Victory.1"] = "Потеря стартового города",
            ["S.Victory.2"] = "Удержание города",
            ["S.Victory.3"] = "Турнир",
            ["S.MapExp"]    = "(эксперим.)",

            // ── Preset group headers ──
            ["S.PG.Classic"]    = "1v1 — Классика",
            ["S.PG.SingleHero"] = "1v1 — Один герой",
            ["S.PG.FFA"]        = "FFA / мультиплеер",
            ["S.PG.PvE"]        = "ПвЕ — 1 против ИИ",

            // ── Code-behind: always-visible text ──
            ["S.CB.Wip"]        = "⚠️ В разработке — некоторые сгенерированные шаблоны могут содержать критические для игры ошибки.",
            ["S.CB.Untitled"]   = "Без имени",
            ["S.CB.Restore"]    = "Восстановить",
            ["S.CB.Maximize"]   = "Развернуть",
            // Validation
            ["S.CB.V.HeroMinMax"]   = "Минимум героев не может превышать максимум.",
            ["S.CB.V.MaxZones"]     = "Всего зон (игроки + нейтральные) не может превышать {0}.",
            ["S.CB.V.NameEmpty"]    = "Название шаблона не может быть пустым.",
            ["S.CB.V.DefaultName"]  = "Шаблон всё ещё использует имя по умолчанию \"Свой шаблон\". Переименуйте его перед сохранением.",
            ["S.CB.V.ZoneTooSmall"] = "Оценочный размер зоны слишком мал. Игра может зависнуть при загрузке карты. Увеличьте размер карты или уменьшите число зон.",
            ["S.CB.V.ExpSize"]      = "Экспериментальные размеры выше 240x240 не подтверждены официальными шаблонами; карты могут не загрузиться, зависнуть или вести себя непредсказуемо.",
            ["S.CB.V.ManyCastles"]  = "Более 1 замка на зону при более чем 10 зонах может привести к зависанию игры при генерации карты. Уменьшите число замков.",
            ["S.CB.V.MinSepIgnored"]= "Минимальное нейтральное разделение нельзя гарантировать при текущей топологии, числе нейтр. зон или настройке порталов; эта опция будет проигнорирована.",
            ["S.CB.V.CityHoldNeedNeutral"] = "Для «Удержания города» нужна хотя бы одна нейтральная зона. Добавьте нейтральную зону или выберите топологию «Хаб».",
            ["S.CB.V.NeutralOnlyNeed"]     = "\"Соединять только через нейтральные зоны\" требует хотя бы одну нейтральную зону. Добавьте нейтральную зону или отключите эту опцию.",
            ["S.CB.V.Tournament2"]  = "Режим турнира поддерживает ровно 2 игроков.",
            ["S.CB.V.TournamentEven"] = "Режим турнира требует, чтобы число зон каждого типа делилось на 2 для честной раскладки. Нечётное: {0}.",
            ["S.CB.V.GuardHigh"]    = "Сила охраны границ/порталов выше 100% может затруднить лёгким и средним ИИ-противникам прохождение — охрана станет слишком сильной.",
            ["S.CB.Tier.WeakNo"]    = "Слабая (без замка)",
            ["S.CB.Tier.WeakYes"]   = "Слабая (с замком)",
            ["S.CB.Tier.MedNo"]     = "Средняя (без замка)",
            ["S.CB.Tier.MedYes"]    = "Средняя (с замком)",
            ["S.CB.Tier.StrongNo"]  = "Сильная (без замка)",
            ["S.CB.Tier.StrongYes"] = "Сильная (с замком)",
            ["S.CB.BanItems"]       = "Бан предметов",
            ["S.CB.BanHeroes"]      = "Бан героев",

            // ── Pickers / update / bonus dialogs (code-behind) ──
            ["S.P.AddSelected"]  = "Добавить выбранное",
            ["S.P.AddSelectedN"] = "Добавить выбранное ({0})",
            ["S.Upd.DownTitle"]  = "Загрузка AuroraRMG {0}",
            ["S.Upd.Loading"]    = "Загрузка…",
            ["S.Upd.Pct"]        = "Загружено {0}%",
            ["S.Upd.OfMb"]       = "  ({0} из {1} МБ)",
            ["S.Upd.ConnGitHub"] = "Подключение к GitHub…",
            ["S.Upd.Preparing"]  = "Подготовка к установке…",
            ["S.Upd.Failed"]     = "Не удалось загрузить обновление:\n\n{0}\n\nМожно скачать новую версию вручную со страницы релизов на GitHub.",
            ["S.Upd.Available"]  = "Доступна новая версия AuroraRMG {0}  ·  установлена {1}.",
            ["S.Upd.RelPage"]    = "Страница релиза",
            ["S.Bonus.AmtGold"]     = "Кол-во золота",
            ["S.Bonus.AmtGems"]     = "Кол-во самоцветов",
            ["S.Bonus.AmtCrystals"] = "Кол-во кристаллов",
            ["S.Bonus.AmtMercury"]  = "Кол-во ртути",
            ["S.Bonus.AmtWood"]     = "Кол-во древесины",
            ["S.Bonus.AmtOre"]      = "Кол-во руды",
            ["S.Bonus.ChooseItem"]  = "Выбор стартового предмета",
            ["S.Bonus.SelectSpellFirst"] = "Сначала выберите заклинание.",
            ["S.Bonus.Validation"]  = "Проверка",
            ["S.Bonus.EnterArtifactId"] = "Введите или выберите ID артефакта.",
            ["S.Bonus.AlreadyAdded"] = "Этот бонус уже добавлен.",
            ["S.Bonus.Duplicate"]    = "Дубликат",

            // ── MainWindow dialogs (code-behind) ──
            ["S.D.SaveSettingsErr"] = "Не удалось сохранить настройки:\n{0}",
            ["S.D.SaveErrTitle"]    = "Ошибка сохранения",
            ["S.D.ResetConfirm"]    = "Сбросить все настройки по умолчанию?",
            ["S.D.ResetTitle"]      = "Новые настройки",
            ["S.D.OpenTitle"]       = "Открыть файл настроек",
            ["S.D.SettingsFilter"]  = "Настройки шаблона (*.oetgs)|*.oetgs|Все файлы (*.*)|*.*",
            ["S.D.FileEmpty"]       = "Файл пуст или повреждён.",
            ["S.D.OpenErr"]         = "Не удалось открыть настройки:\n{0}",
            ["S.D.OpenErrTitle"]    = "Ошибка открытия",
            ["S.D.SaveAsTitle"]     = "Сохранить настройки как",
            ["S.D.MySettings"]      = "Мои настройки",
            ["S.D.SaveTplTitle"]    = "Сохранить шаблон",
            ["S.D.TplFilter"]       = "Шаблон RMG (*.rmg.json)|*.rmg.json",
            ["S.D.ExpectedPath"]    = "Ожидается:\n{0}\n\n",
            ["S.D.ExpectedStruct"]  = "Ожидаемая структура папок:\n...\\HeroesOldenEra_Data\\StreamingAssets\\map_templates\n\n",
            ["S.D.WrongFolderMsg"]  = "Файл сохраняется вне ожидаемой папки шаблонов.\n\n{0}Выбрано:\n{1}\n\nШаблоны, сохранённые в другом месте, не появятся в игре. Всё равно сохранить здесь?",
            ["S.D.WrongFolderTitle"]= "Неверная папка",
            ["S.D.NameMismatchMsg"] = "Файл будет сохранён как \"{0}\", но в игре шаблон будет называться \"{1}\".\n\n«Да» — сохранить как есть, «Нет» — вернуться и переименовать шаблон.",
            ["S.D.NameMismatchTitle"] = "Несовпадение имени шаблона",
            ["S.D.SavedMsg"]        = "Шаблон успешно сохранён:\n\n{0}",
            ["S.D.SavedPreview"]    = "\n\nПревью PNG сохранено:\n\n{0}",
            ["S.D.SavedPreviewErr"] = "\n\nШаблон сохранён, но превью PNG записать не удалось:\n{0}",
            ["S.D.SavedHint"]       = "\n\n\n💡 Подсказка: шаблоны должны лежать в:\n<папка установки Olden Era>\\HeroesOldenEra_Data\\StreamingAssets\\map_templates",
            ["S.D.SavedTitle"]      = "Сохранено",

            // ── Game-asset opt-in dialog ──
            ["S.GA.DisclaimerMsg"] = "AuroraRMG прочитает локальные файлы установленной игры (Core.zip), чтобы показать полный список героев с настоящими именами.\n\n• Файлы только читаются — ничего не изменяется и никуда не загружается.\n• Нужна установленная игра (определяется через Steam).\n• Результат кешируется локально, поэтому делается один раз.\n\nПодключить ассеты игры?",
            ["S.GA.DisclaimerTitle"] = "Подключение ассетов игры",
            ["S.GA.NotFoundMsg"] = "Установленная игра не найдена — продолжаю использовать встроенный список героев. Если игра установлена в нестандартном месте, сообщите — добавим выбор папки вручную.",
            ["S.GA.NotFoundTitle"] = "Игра не найдена",
            ["S.GA.ConnectedMsg"] = "Подключено: найдено героев — {0}. Откройте «+» в списке банов героев, чтобы выбрать из полного списка.",
            ["S.GA.ConnectedTitle"] = "Ассеты подключены",

            // ── Zone editor (code-behind) ──
            ["S.EC.Status0"]       = "Зон: {0}, связей: {1}",
            ["S.EC.NewTemplate"]   = "Новый шаблон",
            ["S.EC.Zone"]          = "Зона",
            ["S.EC.Name"]          = "Имя",
            ["S.EC.Size"]          = "Размер",
            ["S.EC.Layout"]        = "Раскладка (layout)",
            ["S.EC.Diplomacy"]     = "Модиф. дипломатии",
            ["S.EC.GuardMult"]     = "Множитель охраны",
            ["S.EC.ConnCount"]     = "Связей у зоны",
            ["S.EC.Conn"]          = "Связь",
            ["S.EC.From"]          = "От",
            ["S.EC.To"]            = "К",
            ["S.EC.Type"]          = "Тип",
            ["S.EC.GuardValue"]    = "Сила охраны",
            ["S.EC.Road"]          = "Дорога",
            ["S.EC.NameTaken"]     = "Имя «{0}» уже занято.",
            ["S.EC.ZoneMoved"]     = "Зона «{0}» перемещена (раскладка — для наглядности, в .rmg.json не сохраняется).",
            ["S.EC.ConnectFrom"]   = "Связать: из «{0}» — выберите вторую зону.",
            ["S.EC.ConnectCancelled"] = "Связывание отменено.",
            ["S.EC.ConnAdded"]     = "Добавлена связь «{0}» → «{1}».",
            ["S.EC.ConnectModeOn"] = "Режим связывания: выберите две зоны.",
            ["S.EC.ConnectModeOff"]= "Режим связывания выключен.",
            ["S.EC.ZoneAdded"]     = "Добавлена зона «{0}».",
            ["S.EC.ZoneDeleted"]   = "Удалена зона «{0}» и {1} связ.",
            ["S.EC.ConnDeleted"]   = "Удалена связь «{0}» → «{1}».",
            ["S.EC.NothingToDelete"] = "Нечего удалять — ничего не выбрано.",
            ["S.EC.NoIssues"]      = "✓ Проблем не найдено.",
            ["S.EC.NoIssuesMsg"]   = "Проблем не найдено. Граф зон корректен.",
            ["S.EC.ValidateTitle"] = "Проверка",
            ["S.EC.IssuesFound"]   = "Найдено проблем: {0}.",
            ["S.EC.IssuesTitle"]   = "Проблемы ({0})",
            ["S.EC.Relayout"]      = "Раскладка пересчитана.",
            ["S.EC.LoadTitle"]     = "Загрузить шаблон",
            ["S.EC.LoadFilter"]    = "Шаблон RMG (*.rmg.json)|*.rmg.json|Все файлы (*.*)|*.*",
            ["S.EC.LoadFail"]      = "Не удалось прочитать шаблон.",
            ["S.EC.Loaded"]        = "Загружено: {0} — зон: {1}, связей: {2}.",
            ["S.EC.LoadErr"]       = "Ошибка загрузки:\n{0}",
            ["S.EC.Error"]         = "Ошибка",
            ["S.EC.SaveValidate"]  = "Найдено проблем: {0}. Сохранить всё равно?\n\n{1}",
            ["S.EC.SaveValidateTitle"] = "Проверка перед сохранением",
            ["S.EC.SaveTitle"]     = "Сохранить шаблон",
            ["S.EC.SaveFilter"]    = "Шаблон RMG (*.rmg.json)|*.rmg.json",
            ["S.EC.Saved"]         = "Сохранено: {0}.",
            ["S.EC.SaveErr"]       = "Ошибка сохранения:\n{0}",
            ["S.EC.WinTitle"]      = "Визуальный редактор зон — {0}",
            ["S.EC.UnsavedMsg"]    = "Есть несохранённые изменения. Закрыть без сохранения?",
            ["S.EC.UnsavedTitle"]  = "Несохранённые изменения",
            // Zone-graph validator
            ["S.V.NoName"]    = "• Зона без имени.",
            ["S.V.DupName"]   = "• Дублирующееся имя зоны: «{0}».",
            ["S.V.Dangling"]  = "• Связь ссылается на несуществующую зону «{0}».",
            ["S.V.SelfLoop"]  = "• Связь зоны «{0}» сама на себя.",
            ["S.V.Isolated"]  = "• Изолированная зона (нет связей): «{0}».",
        };

        public static readonly Dictionary<string, string> En = new()
        {
            // ── UI chrome (curated) ──
            ["S.Tab.Rules"]        = "Rules",
            ["S.Tab.MapZones"]     = "Map & Zones",
            ["S.Tab.BonusesBans"]  = "Bonuses & Bans",
            ["S.Tab.ExtraContent"] = "Extra Content [EXP.]",
            ["S.Hdr.Template"]     = "◆  TEMPLATE",
            ["S.Hdr.Heroes"]       = "◆  HEROES",
            ["S.Hdr.GameRules"]    = "◆  GAME RULES",
            ["S.Hdr.Environment"]  = "◆  ENVIRONMENT & ENCOUNTERS",
            ["S.Lbl.Preset"]       = "Preset",
            ["S.Btn.PresetPick"]   = "— Choose a ready-made template —   ▾",
            ["S.Lbl.TemplateName"] = "Template name",
            ["S.Lbl.MapSize"]      = "Map size",
            ["S.Chk.ExpMaps"]      = "Experimental large maps",
            ["S.Lbl.Players"]      = "Players",
            ["S.Lbl.HeroMin"]      = "Starting hero limit",
            ["S.Lbl.HeroMax"]      = "Max hero limit",
            ["S.Lbl.HeroIncrement"]= "Limit gain per town",
            ["S.Chk.SingleHero"]   = "Single-hero mode",
            ["S.Hint.Heroes"]      = "Slider, −/+ buttons or type a number (Enter). Maximum is 12 (as in the official game templates).",
            ["S.Btn.Generate"]     = "⚔  Create template",
            ["S.Btn.SaveTemplate"] = "💾  Save template",
            ["S.Btn.Editor"]       = "🗺 Editor",
            ["S.Chk.ShowPreview"]  = "Show preview",

            // ── MainWindow (extracted) ──
            ["S.M.001"] = "Reset settings (Ctrl+N)",
            ["S.M.002"] = "Open settings (Ctrl+O)",
            ["S.M.003"] = "Save settings (Ctrl+S)",
            ["S.M.004"] = "Save settings as… (Ctrl+Shift+S)",
            ["S.M.005"] = "Visual zone editor (open the current template or load a .rmg.json)",
            ["S.M.006"] = "Russian language",
            ["S.M.007"] = "Minimize",
            ["S.M.008"] = "Maximize",
            ["S.M.009"] = "Close",
            ["S.M.010"] = "Update",
            ["S.M.011"] = "What's new",
            ["S.M.012"] = "Later",
            ["S.M.013"] = "Quick start: ready-made configurations grouped by mode type",
            ["S.M.014"] = "Custom template",
            ["S.M.015"] = "Adds sizes from 256x256 to 512x512. Official templates stop at 240x240, so larger maps may fail to load, freeze or behave unpredictably.",
            ["S.M.016"] = "Less",
            ["S.M.017"] = "You can type a custom value (Enter)",
            ["S.M.018"] = "More",
            ["S.M.019"] = "Main victory condition",
            ["S.M.020"] = "Faction-laws experience",
            ["S.M.021"] = "Astrology experience",
            ["S.M.022"] = "Defeat on losing the starting town",
            ["S.M.023"] = "Town-loss day",
            ["S.M.024"] = "Defeat on losing the starting hero",
            ["S.M.025"] = "Victory by holding a neutral town",
            ["S.M.026"] = "Days to hold",
            ["S.M.027"] = "Gladiator arena rules",
            ["S.M.028"] = "Arena delay",
            ["S.M.029"] = "Arena scoring day",
            ["S.M.030"] = "Tournament rules",
            ["S.M.031"] = "Points to win",
            ["S.M.032"] = "First battle on day ",
            ["S.M.033"] = "Days between battles",
            ["S.M.034"] = "Keep the whole army after battle",
            ["S.M.035"] = "Terrain type",
            ["S.M.036"] = "Monster aggression",
            ["S.M.037"] = "Water amount",
            ["S.M.038"] = "Neutral join chance",
            ["S.M.039"] = "Terrain roughness",
            ["S.M.040"] = "Lake amount",
            ["S.M.041"] = "Allow guard bypass (holes)",
            ["S.M.042"] = "◆  TOPOLOGY",
            ["S.M.043"] = "Map topology",
            ["S.M.044"] = "Hub zone size",
            ["S.M.045"] = "Towns in hub",
            ["S.M.046"] = "Connect only via neutral zones when possible",
            ["S.M.047"] = "The game tries to connect player zones only through neutral zones. If no neutral zone is nearby, a direct connection to another player is made.",
            ["S.M.048"] = "◆  ZONE SETUP",
            ["S.M.049"] = "Advanced settings",
            ["S.M.050"] = "Extra neutral zones",
            ["S.M.051"] = "Towns in player zones",
            ["S.M.052"] = "Single faction for all towns in a player zone",
            ["S.M.053"] = "Player starts owning all towns in their zone",
            ["S.M.054"] = "Towns in neutral zones",
            ["S.M.055"] = "Resource frequency",
            ["S.M.056"] = "Structure frequency",
            ["S.M.057"] = "Neutral army strength",
            ["S.M.058"] = "Border/portal strength",
            ["S.M.059"] = "Neutral zones",
            ["S.M.060"] = "Neutral zones with a town use the \"Towns in neutral zones\" value.",
            ["S.M.061"] = "Weak neutral, no town",
            ["S.M.062"] = "Weak neutral, with town",
            ["S.M.063"] = "Medium neutral, no town",
            ["S.M.064"] = "Medium neutral, with town",
            ["S.M.065"] = "Strong neutral, no town",
            ["S.M.066"] = "Strong neutral, with town",
            ["S.M.067"] = "Min. neutrals between players",
            ["S.M.068"] = "Applied only if the chosen topology, neutral-zone count and portal settings allow it; otherwise the normal connection layout is used.",
            ["S.M.069"] = "Generate roads",
            ["S.M.070"] = "Create remote footholds",
            ["S.M.071"] = "Create extra portals",
            ["S.M.072"] = "Max portal count",
            ["S.M.073"] = "Zone fine-tuning [EXPERIMENTAL]",
            ["S.M.074"] = "Relative region weights and guard spread for the game's layout.",
            ["S.M.075"] = "Player zone size",
            ["S.M.076"] = "Neutral zone size",
            ["S.M.077"] = "Guard strength spread",
            ["S.M.078"] = "◆  STARTING BONUSES",
            ["S.M.079"] = "Bonuses are granted equally to all players at the start.",
            ["S.M.080"] = "Remove",
            ["S.M.081"] = "◆  BANS",
            ["S.M.082"] = "Connect the installed game's assets (full hero list with names)",
            ["S.M.083"] = "Without this option the editor works fully: a built-in verified list and coloured faction markers. With it, the full hero list with real names is loaded from the game's local files; nothing is uploaded to the network.",
            ["S.M.084"] = "Banned items",
            ["S.M.085"] = "Banned spells",
            ["S.M.086"] = "Banned heroes",
            ["S.M.087"] = "◆  ADVANCED",
            ["S.M.088"] = "Guard-value overrides (one per line: sid=value)",
            ["S.M.089"] = "Experimental feature. The generator will try to additionally place everything per these rules, but is limited by available space. Too much mandatory content can cause unpredictable behaviour, especially on small maps and with small player zones.",
            ["S.M.090"] = "Player zones",
            ["S.M.091"] = "◆  Mines",
            ["S.M.092"] = "Add",
            ["S.M.093"] = "◆  Treasures",
            ["S.M.094"] = "◆  Creature recruitment",
            ["S.M.095"] = "◆  Resource banks",
            ["S.M.096"] = "◆  Utility structures",
            ["S.M.097"] = "◆  Hero development structures",
            ["S.M.098"] = "Remove content",
            ["S.M.099"] = "Guarded",
            ["S.M.100"] = "By the town",
            ["S.M.101"] = "Road",
            ["S.M.102"] = "Any",
            ["S.M.103"] = "Adjacent",
            ["S.M.104"] = "Near",
            ["S.M.105"] = "Medium",
            ["S.M.106"] = "Far",
            ["S.M.107"] = "Very far",
            ["S.M.108"] = "Reset to default",
            ["S.M.109"] = "Weak neutral zones",
            ["S.M.110"] = "Medium neutral zones",
            ["S.M.111"] = "Strong neutral zones",
            ["S.M.112"] = "Hub zones",
            ["S.M.113"] = "⚠️ Settings changed — create a new template before saving to apply the changes.",

            // ── Zone editor (extracted) ──
            ["S.Ed.001"] = "🗺  Zone editor",
            ["S.Ed.002"] = "📂 Load .rmg.json",
            ["S.Ed.003"] = "➕ Zone",
            ["S.Ed.004"] = "🔗 Connect",
            ["S.Ed.005"] = "🗑 Delete",
            ["S.Ed.006"] = "✓ Validate",
            ["S.Ed.007"] = "💾 Save .rmg.json",
            ["S.Ed.008"] = "⟲ Reset view",
            ["S.Ed.009"] = "↺ Auto-layout",
            ["S.Ed.010"] = "◆  INSPECTOR",
            ["S.Ed.011"] = "Select a zone or connection on the canvas.",
            ["S.Ed.012"] = "Ready.",
            ["S.Ed.ZoomIn"]  = "Zoom in",
            ["S.Ed.ZoomOut"] = "Zoom out",
            ["S.Ed.LegZones"]   = "Zones:",
            ["S.Ed.LegPlayer"]  = "player",
            ["S.Ed.LegHub"]     = "hub",
            ["S.Ed.LegNeutral"] = "neutral",
            ["S.Ed.LegConns"]   = "Connections:",
            ["S.Ed.LegDirect"]  = "direct",
            ["S.Ed.LegPortal"]  = "portal",
            ["S.Ed.CanvasHint"] = "Wheel — zoom · drag background — pan · drag a zone · Del — delete · Esc — cancel",
            ["S.Ed.ExportPng"]    = "🖼 PNG",
            ["S.EC.ExportTitle"]  = "Export graph to PNG",
            ["S.EC.Exported"]     = "Image saved: {0}.",

            // ── Spell picker (extracted) ──
            ["S.Spell.001"] = "Select a spell",
            ["S.Spell.002"] = "Free (0 mana)",
            ["S.Spell.003"] = "Add selected",
            ["S.Spell.004"] = "Cancel",

            // ── Item/ban picker (extracted) ──
            ["S.Item.001"] = "Select to ban",
            ["S.Item.002"] = "Custom ID:",
            ["S.Item.003"] = "Enter any ID not in the list above",
            ["S.Item.004"] = "Add custom",

            // ── Bonus picker (extracted) ──
            ["S.Bonus.001"] = "Add bonus",
            ["S.Bonus.002"] = "Bonus type",
            ["S.Bonus.003"] = "Spell",
            ["S.Bonus.004"] = "Army multiplier",
            ["S.Bonus.005"] = "Movement bonus",
            ["S.Bonus.006"] = "Starting item",
            ["S.Bonus.007"] = "Starting gold",
            ["S.Bonus.008"] = "Starting gems",
            ["S.Bonus.009"] = "Starting crystals",
            ["S.Bonus.010"] = "Starting mercury",
            ["S.Bonus.011"] = "Starting wood",
            ["S.Bonus.012"] = "Starting ore",
            ["S.Bonus.013"] = "Applies to",
            ["S.Bonus.014"] = "Starting hero",
            ["S.Bonus.015"] = "All heroes",
            ["S.Bonus.016"] = "Choose…",
            ["S.Bonus.017"] = "Make the spell free (0 mana)",
            ["S.Bonus.018"] = "Multiplier (e.g. 2 = doubled starting army)",
            ["S.Bonus.019"] = "Extra movement tiles (0 = default)",
            ["S.Bonus.020"] = "Artifact ID",
            ["S.Bonus.021"] = "Amount",

            // ── Update progress (extracted) ──
            ["S.Upd.001"] = "AuroraRMG update",
            ["S.Upd.002"] = "Downloading update…",
            ["S.Upd.003"] = "Connecting…",

            // ── Value-override picker (extracted) ──
            ["S.Vov.001"] = "Value overrides",
            ["S.Vov.002"] = "Guard value for the selected:",
            ["S.Vov.003"] = "Guard value for all checked objects",

            // ── Option combos (Rules / Map tabs) ──
            ["S.Topo.Balanced"] = "Balanced",
            ["S.Topo.Random"]   = "Random",
            ["S.Topo.Ring"]     = "Ring",
            ["S.Topo.Hub"]      = "Hub",
            ["S.Topo.Chain"]    = "Chain",
            ["S.TopoDesc.Balanced"] = "Zones are placed in concentric rings by quality tier. Players on the outer ring, neutral zones on the inner ones. Each zone connects to its neighbours on adjacent rings.",
            ["S.TopoDesc.Random"]   = "Zones are placed at random positions. Each zone connects to all bordering zones — no fixed structure.",
            ["S.TopoDesc.Ring"]     = "All zones arranged in a circle. Each zone connects to its two neighbours.",
            ["S.TopoDesc.Hub"]      = "All zones connect to a shared central hub. Players never border each other directly.",
            ["S.TopoDesc.Chain"]    = "Zones connected in a straight line from one end to the other, without closing the loop.",
            ["S.Terrain.FactionBased"] = "By faction",
            ["S.Terrain.Random"]       = "Random mix",
            ["S.Terrain.Grass"]        = "Grass",
            ["S.Terrain.Snow"]         = "Snow",
            ["S.Terrain.Lava"]         = "Lava",
            ["S.Terrain.Sand"]         = "Sand",
            ["S.Terrain.Dirt"]         = "Dirt",
            ["S.Terrain.Deathland"]    = "Deathland",
            ["S.Terrain.Autumn"]       = "Autumn",
            ["S.Aggr.Passive"]    = "Passive",
            ["S.Aggr.Normal"]     = "Normal",
            ["S.Aggr.Aggressive"] = "Aggressive",
            ["S.Water.None"]   = "None",
            ["S.Water.Small"]  = "Some",
            ["S.Water.Medium"] = "Medium",
            ["S.Water.Large"]  = "Lots",
            ["S.Victory.0"] = "Standard",
            ["S.Victory.1"] = "Loss of the starting town",
            ["S.Victory.2"] = "City hold",
            ["S.Victory.3"] = "Tournament",
            ["S.MapExp"]    = "(experimental)",

            // ── Preset group headers ──
            ["S.PG.Classic"]    = "1v1 — Classic",
            ["S.PG.SingleHero"] = "1v1 — Single hero",
            ["S.PG.FFA"]        = "FFA / multiplayer",
            ["S.PG.PvE"]        = "PvE — 1 vs AI",

            // ── Code-behind: always-visible text ──
            ["S.CB.Wip"]        = "⚠️ Work in progress — some generated templates may contain game-critical errors.",
            ["S.CB.Untitled"]   = "Untitled",
            ["S.CB.Restore"]    = "Restore",
            ["S.CB.Maximize"]   = "Maximize",
            // Validation
            ["S.CB.V.HeroMinMax"]   = "Minimum heroes cannot exceed the maximum.",
            ["S.CB.V.MaxZones"]     = "Total zones (players + neutral) cannot exceed {0}.",
            ["S.CB.V.NameEmpty"]    = "Template name cannot be empty.",
            ["S.CB.V.DefaultName"]  = "The template still uses the default name \"Custom template\". Rename it before saving.",
            ["S.CB.V.ZoneTooSmall"] = "Estimated zone size is too small. The game may freeze while loading the map. Increase the map size or reduce the number of zones.",
            ["S.CB.V.ExpSize"]      = "Experimental sizes above 240x240 aren't backed by official templates; maps may fail to load, freeze or behave unpredictably.",
            ["S.CB.V.ManyCastles"]  = "More than 1 town per zone with more than 10 zones can freeze the game during map generation. Reduce the number of towns.",
            ["S.CB.V.MinSepIgnored"]= "The minimum neutral separation can't be guaranteed with the current topology, neutral-zone count or portal setting; this option will be ignored.",
            ["S.CB.V.CityHoldNeedNeutral"] = "\"City hold\" needs at least one neutral zone. Add a neutral zone or choose the \"Hub\" topology.",
            ["S.CB.V.NeutralOnlyNeed"]     = "\"Connect only via neutral zones\" requires at least one neutral zone. Add a neutral zone or disable this option.",
            ["S.CB.V.Tournament2"]  = "Tournament mode supports exactly 2 players.",
            ["S.CB.V.TournamentEven"] = "Tournament mode requires each tier's zone count to be divisible by 2 for a fair layout. Odd: {0}.",
            ["S.CB.V.GuardHigh"]    = "Border/portal guard strength above 100% can make it hard for easy and medium AI opponents to break through — guards become too strong.",
            ["S.CB.Tier.WeakNo"]    = "Weak (no town)",
            ["S.CB.Tier.WeakYes"]   = "Weak (with town)",
            ["S.CB.Tier.MedNo"]     = "Medium (no town)",
            ["S.CB.Tier.MedYes"]    = "Medium (with town)",
            ["S.CB.Tier.StrongNo"]  = "Strong (no town)",
            ["S.CB.Tier.StrongYes"] = "Strong (with town)",
            ["S.CB.BanItems"]       = "Ban items",
            ["S.CB.BanHeroes"]      = "Ban heroes",

            // ── Pickers / update / bonus dialogs (code-behind) ──
            ["S.P.AddSelected"]  = "Add selected",
            ["S.P.AddSelectedN"] = "Add selected ({0})",
            ["S.Upd.DownTitle"]  = "Downloading AuroraRMG {0}",
            ["S.Upd.Loading"]    = "Downloading…",
            ["S.Upd.Pct"]        = "Downloaded {0}%",
            ["S.Upd.OfMb"]       = "  ({0} of {1} MB)",
            ["S.Upd.ConnGitHub"] = "Connecting to GitHub…",
            ["S.Upd.Preparing"]  = "Preparing to install…",
            ["S.Upd.Failed"]     = "Failed to download the update:\n\n{0}\n\nYou can download the new version manually from the GitHub releases page.",
            ["S.Upd.Available"]  = "A new version of AuroraRMG {0} is available  ·  installed {1}.",
            ["S.Upd.RelPage"]    = "Release page",
            ["S.Bonus.AmtGold"]     = "Gold amount",
            ["S.Bonus.AmtGems"]     = "Gem amount",
            ["S.Bonus.AmtCrystals"] = "Crystal amount",
            ["S.Bonus.AmtMercury"]  = "Mercury amount",
            ["S.Bonus.AmtWood"]     = "Wood amount",
            ["S.Bonus.AmtOre"]      = "Ore amount",
            ["S.Bonus.ChooseItem"]  = "Choose starting item",
            ["S.Bonus.SelectSpellFirst"] = "Select a spell first.",
            ["S.Bonus.Validation"]  = "Validation",
            ["S.Bonus.EnterArtifactId"] = "Enter or choose an artifact ID.",
            ["S.Bonus.AlreadyAdded"] = "This bonus is already added.",
            ["S.Bonus.Duplicate"]    = "Duplicate",

            // ── MainWindow dialogs (code-behind) ──
            ["S.D.SaveSettingsErr"] = "Failed to save settings:\n{0}",
            ["S.D.SaveErrTitle"]    = "Save error",
            ["S.D.ResetConfirm"]    = "Reset all settings to defaults?",
            ["S.D.ResetTitle"]      = "New settings",
            ["S.D.OpenTitle"]       = "Open settings file",
            ["S.D.SettingsFilter"]  = "Template settings (*.oetgs)|*.oetgs|All files (*.*)|*.*",
            ["S.D.FileEmpty"]       = "The file is empty or corrupted.",
            ["S.D.OpenErr"]         = "Failed to open settings:\n{0}",
            ["S.D.OpenErrTitle"]    = "Open error",
            ["S.D.SaveAsTitle"]     = "Save settings as",
            ["S.D.MySettings"]      = "My settings",
            ["S.D.SaveTplTitle"]    = "Save template",
            ["S.D.TplFilter"]       = "RMG template (*.rmg.json)|*.rmg.json",
            ["S.D.ExpectedPath"]    = "Expected:\n{0}\n\n",
            ["S.D.ExpectedStruct"]  = "Expected folder structure:\n...\\HeroesOldenEra_Data\\StreamingAssets\\map_templates\n\n",
            ["S.D.WrongFolderMsg"]  = "The file is being saved outside the expected templates folder.\n\n{0}Chosen:\n{1}\n\nTemplates saved elsewhere won't appear in the game. Save here anyway?",
            ["S.D.WrongFolderTitle"]= "Wrong folder",
            ["S.D.NameMismatchMsg"] = "The file will be saved as \"{0}\", but in-game the template will be named \"{1}\".\n\n\"Yes\" — save as is, \"No\" — go back and rename the template.",
            ["S.D.NameMismatchTitle"] = "Template name mismatch",
            ["S.D.SavedMsg"]        = "Template saved successfully:\n\n{0}",
            ["S.D.SavedPreview"]    = "\n\nPNG preview saved:\n\n{0}",
            ["S.D.SavedPreviewErr"] = "\n\nTemplate saved, but the PNG preview could not be written:\n{0}",
            ["S.D.SavedHint"]       = "\n\n\n💡 Tip: templates must live in:\n<Olden Era install folder>\\HeroesOldenEra_Data\\StreamingAssets\\map_templates",
            ["S.D.SavedTitle"]      = "Saved",

            // ── Game-asset opt-in dialog ──
            ["S.GA.DisclaimerMsg"] = "AuroraRMG will read the installed game's local files (Core.zip) to show the full hero list with real names.\n\n• Files are read only — nothing is changed or uploaded.\n• The installed game is required (detected via Steam).\n• The result is cached locally, so this is done once.\n\nConnect game assets?",
            ["S.GA.DisclaimerTitle"] = "Connect game assets",
            ["S.GA.NotFoundMsg"] = "The installed game wasn't found — keeping the built-in hero list. If the game is installed in a non-standard location, let us know and we'll add a manual folder picker.",
            ["S.GA.NotFoundTitle"] = "Game not found",
            ["S.GA.ConnectedMsg"] = "Connected: {0} heroes found. Open \"+\" in the hero-bans list to pick from the full roster.",
            ["S.GA.ConnectedTitle"] = "Assets connected",

            // ── Zone editor (code-behind) ──
            ["S.EC.Status0"]       = "Zones: {0}, connections: {1}",
            ["S.EC.NewTemplate"]   = "New template",
            ["S.EC.Zone"]          = "Zone",
            ["S.EC.Name"]          = "Name",
            ["S.EC.Size"]          = "Size",
            ["S.EC.Layout"]        = "Layout",
            ["S.EC.Diplomacy"]     = "Diplomacy modifier",
            ["S.EC.GuardMult"]     = "Guard multiplier",
            ["S.EC.ConnCount"]     = "Connections",
            ["S.EC.Conn"]          = "Connection",
            ["S.EC.From"]          = "From",
            ["S.EC.To"]            = "To",
            ["S.EC.Type"]          = "Type",
            ["S.EC.GuardValue"]    = "Guard value",
            ["S.EC.Road"]          = "Road",
            ["S.EC.NameTaken"]     = "The name \"{0}\" is already taken.",
            ["S.EC.ZoneMoved"]     = "Zone \"{0}\" moved (layout is for clarity only; not saved to .rmg.json).",
            ["S.EC.ConnectFrom"]   = "Connect: from \"{0}\" — pick the second zone.",
            ["S.EC.ConnectCancelled"] = "Connecting cancelled.",
            ["S.EC.ConnAdded"]     = "Connection added: \"{0}\" → \"{1}\".",
            ["S.EC.ConnectModeOn"] = "Connect mode: pick two zones.",
            ["S.EC.ConnectModeOff"]= "Connect mode off.",
            ["S.EC.ZoneAdded"]     = "Zone \"{0}\" added.",
            ["S.EC.ZoneDeleted"]   = "Removed zone \"{0}\" and {1} connection(s).",
            ["S.EC.ConnDeleted"]   = "Removed connection \"{0}\" → \"{1}\".",
            ["S.EC.NothingToDelete"] = "Nothing to delete — nothing is selected.",
            ["S.EC.NoIssues"]      = "✓ No issues found.",
            ["S.EC.NoIssuesMsg"]   = "No issues found. The zone graph is valid.",
            ["S.EC.ValidateTitle"] = "Validation",
            ["S.EC.IssuesFound"]   = "Issues found: {0}.",
            ["S.EC.IssuesTitle"]   = "Issues ({0})",
            ["S.EC.Relayout"]      = "Layout recomputed.",
            ["S.EC.LoadTitle"]     = "Load template",
            ["S.EC.LoadFilter"]    = "RMG template (*.rmg.json)|*.rmg.json|All files (*.*)|*.*",
            ["S.EC.LoadFail"]      = "Couldn't read the template.",
            ["S.EC.Loaded"]        = "Loaded: {0} — zones: {1}, connections: {2}.",
            ["S.EC.LoadErr"]       = "Load error:\n{0}",
            ["S.EC.Error"]         = "Error",
            ["S.EC.SaveValidate"]  = "Issues found: {0}. Save anyway?\n\n{1}",
            ["S.EC.SaveValidateTitle"] = "Validation before saving",
            ["S.EC.SaveTitle"]     = "Save template",
            ["S.EC.SaveFilter"]    = "RMG template (*.rmg.json)|*.rmg.json",
            ["S.EC.Saved"]         = "Saved: {0}.",
            ["S.EC.SaveErr"]       = "Save error:\n{0}",
            ["S.EC.WinTitle"]      = "Visual zone editor — {0}",
            ["S.EC.UnsavedMsg"]    = "There are unsaved changes. Close without saving?",
            ["S.EC.UnsavedTitle"]  = "Unsaved changes",
            // Zone-graph validator
            ["S.V.NoName"]    = "• Zone without a name.",
            ["S.V.DupName"]   = "• Duplicate zone name: \"{0}\".",
            ["S.V.Dangling"]  = "• Connection references a non-existent zone \"{0}\".",
            ["S.V.SelfLoop"]  = "• Self-loop on zone \"{0}\".",
            ["S.V.Isolated"]  = "• Isolated zone (no connections): \"{0}\".",
        };
    }
}
